// /etc/nginx/sites-available/api.conf

server {
    server_name dev.api.example.com;
    location / {
        proxy_pass http://localhost:8081;
    }
}

server {
    server_name staging.api.example.com;
    location / {
        proxy_pass http://localhost:8082;
    }
}

server {
    server_name api.example.com;
    location / {
        proxy_pass http://localhost:8083;
    }
}


// sudo systemctl restart nginx
